import Head from "next/head"
import { Box } from "@chakra-ui/layout"


const Layout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Real Estate</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box maxWidth="1280px" m="auto">
                <header>Navbar</header>
                <main>{children}</main>
                <footer>Footer</footer>
            </Box>
        </div>
    )
}

export default Layout
